---
abstract: 'Make Doxygen support Lua'
author:
  - 'Alec Chen, C<< <alec at cpan.org> >>'
  - 'Alec Chen <alec@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Doxygen-Lua
no_index:
  directory:
    - example
    - inc
    - t
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/alecchen/doxygen-lua
version: 0.04
